#!/bin/bash

#--------------------------------------------------------
# convert video file to avi (MPEG4)
#
# - change the scale parameter (9.11)
# - executed without any argument, show usage info. exit code 2. (9.13)
# 
# Kai Yuan
#--------------------------------------------------------
inputF=
SCALE=800:600
if [ $# == 0 ]; then 
    
    echo -e "\

        Convert video format to avi (MPEG4) using mencoder

        usage: convideo.sh <input video file> [scale]

        scale format: 800:600, 320:240 ...
            "
    exit 2
elif [ ! -f $1 ]; then
    echo " ERROR: cannot find video file:$1"
    exit 1
elif [ ! -z $2 ]; then
    test=$(echo $2 | grep  "^[0-9]\{3,4\}:[0-9]\{3,4\}$")
    if [ -z $test ]; then
        echo "ERROR: scale format is not correct. e.g. 800:600"
        exit 1
    else
        SCALE=$test
        inputF=$1
    fi
fi

mencoder $1 -o $(echo ${inputF%%.*})_NEW.avi  -oac mp3lame -lameopts vbr=3:br=32 -ovc lavc -lavcopts vcodec=mpeg4:mbd=1:vbitrate=1600 -vf scale=$SCALE 2>/dev/null

# extract video!!
#mencoder 'jack.mkv' -ss 01:05:00 -endpos 00:xx:xx -ovc lavc -lavcopts vcodec=mpeg4:vhq:vbitrate=1200 -oac mp3lame -o output.avi
